version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/chat-app
      - PORT=5000
    depends_on:
      - mongodb
    networks:
      - chat-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

volumes:
  mongodb_data:
